import pkg from '../promo30/node_modules/playwright/index.js';
const {chromium} = pkg;
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises';
const out='/workspace/build/docker/list-concat-demo';
const workspace='/workspace/build/docker/list-concat-demo/workspace';
const file=`${workspace}/vehicle.py`; const result=`${workspace}/vehicle-result.txt`;
await mkdir(`${out}/raw-staged`,{recursive:true}); await writeFile(file,''); await rm(result,{force:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1920,height:960},recordVideo:{dir:`${out}/raw-staged`,size:{width:1920,height:960}}});
const page=await context.newPage(); const sleep=ms=>page.waitForTimeout(ms);
await page.goto(`http://ide:9042/?folder=${workspace}`); await page.locator('.monaco-workbench').waitFor(); await sleep(1500);
await page.keyboard.press('Control+p'); let input=page.locator('.quick-input-widget input'); await input.waitFor({state:'visible'}); await input.fill('vehicle.py');
await page.locator('.quick-input-list .monaco-list-row').filter({hasText:'vehicle.py'}).first().click(); await input.waitFor({state:'hidden'}); await sleep(600);
if(await page.locator('.part.sidebar').isVisible()) await page.keyboard.press('Control+b');
await page.keyboard.press('F1'); await input.waitFor({state:'visible'}); await input.fill('>Terminal: Create New Terminal');
await page.locator('.quick-input-list .monaco-list-row').filter({hasText:'Terminal: Create New Terminal'}).first().click(); await input.waitFor({state:'hidden'}); await sleep(700);
const editor=page.locator('.monaco-editor').first();
const typeLines=async lines=>{const b=await editor.boundingBox();await page.mouse.click(b.x+400,b.y+100); for(const line of lines){for(const ch of line){await page.keyboard.insertText(ch);await sleep(18);}await page.keyboard.press('Enter');}await page.keyboard.press('Control+s');};
const run=async()=>{const t=page.locator('.xterm:visible').first();await t.click();await page.keyboard.type('python3 vehicle.py | tee vehicle-result.txt',{delay:12});await page.keyboard.press('Enter');await sleep(1000);};
await page.screenshot({path:`${out}/staged-blank.png`});
await sleep(4500); await typeLines(['vehicle1 = ["train", "bus", "car", "ship"]','vehicle2 = ["subway", "bicycle"]','print(vehicle1, vehicle2)']); await run(); await page.screenshot({path:`${out}/staged-step1.png`});
await sleep(4300); await typeLines(['vehicle = vehicle1 + vehicle2','print(vehicle)']); await run(); await page.screenshot({path:`${out}/staged-step2.png`});
await sleep(4300); await typeLines(['vehicle += ["bike"]','print(vehicle)']); await run(); await page.screenshot({path:`${out}/staged-step3.png`});
await sleep(4300); const video=page.video(); await context.close(); await video.saveAs(`${out}/recording-staged.webm`); await browser.close();
console.log('staged_recorded');
