import pkg from '../promo30/node_modules/playwright/index.js';
const {chromium} = pkg;
import {mkdir, readFile, writeFile, rm} from 'node:fs/promises';
import path from 'node:path';
const out='/workspace/build/docker/list-concat-demo';
const workspace='/workspace/build/docker/list-concat-demo/workspace';
await mkdir(out,{recursive:true}); await rm(`${workspace}/vehicle-result.txt`,{force:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1920,height:960},recordVideo:{dir:`${out}/raw`,size:{width:1920,height:960}}});
const page=await context.newPage();
await page.goto(`http://ide:9042/?folder=${workspace}`); await page.locator('.monaco-workbench').waitFor(); await page.waitForTimeout(1600);
await page.keyboard.press('Control+p'); const input=page.locator('.quick-input-widget input'); await input.waitFor({state:'visible'}); await input.fill('vehicle.py');
await page.locator('.quick-input-list .monaco-list-row').filter({hasText:'vehicle.py'}).first().click(); await input.waitFor({state:'hidden'}); await page.waitForTimeout(800);
if(await page.locator('.part.sidebar').isVisible()) await page.keyboard.press('Control+b');
await page.keyboard.press('F1'); await input.waitFor({state:'visible'}); await input.fill('>Terminal: Create New Terminal');
await page.locator('.quick-input-list .monaco-list-row').filter({hasText:'Terminal: Create New Terminal'}).first().click(); await input.waitFor({state:'hidden'}); await page.waitForTimeout(700);
const terminal=page.locator('.xterm:visible').first(); await terminal.click(); await page.keyboard.type("python3 vehicle.py | tee vehicle-result.txt",{delay:20}); await page.keyboard.press('Enter');
await page.waitForTimeout(1800); await page.screenshot({path:`${out}/ide-result.png`});
await page.waitForTimeout(26000);
const video=page.video(); await context.close(); await video.saveAs(`${out}/recording.webm`); await browser.close();
console.log('recorded');
