import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const dest=path.resolve('../../build/promo30/frames');
await mkdir(dest,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || '/home/jimmyhuang/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage();
page.on('console',msg=>console.log(msg.text()));
page.on('pageerror',e=>console.error('PAGE_ERROR',e));
let count=0;
await page.exposeFunction('saveFrame',async(frame,data)=>{if(frame<900){await writeFile(path.join(dest,`${String(frame).padStart(5,'0')}.png`),Buffer.from(data,'base64'));count++;if(frame%150===0)console.log('FRAME',frame);}});
await page.goto('http://127.0.0.1:9030/render.html');
await page.waitForFunction(()=>window.ready,{timeout:120000});
await page.evaluate(()=>window.startRender());
console.log('DONE',count,await page.evaluate(()=>window.renderResult));
await browser.close();
if(count!==900)process.exitCode=1;
